USE duanmau_atgt;
INSERT IGNORE INTO places (slug, name, type, story, open_hours, ticket, distance_km, age_note, safety_note, art_code, map_x, map_y) VALUES
('tuong-dai-chien-thang','Tượng đài Chiến thắng Buôn Ma Thuột','cong-vien','Ngay giữa vòng xoay Ngã Sáu là chiếc xe tăng thật gắn trên tượng đài — biểu tượng của ngày giải phóng Buôn Ma Thuột 10/3/1975. Đứng ở đây, con đang đứng ngay "trái tim" của thành phố đó!','Cả ngày','Miễn phí',0.1,'Mọi lứa tuổi','Ngã Sáu là vòng xoay ĐÔNG XE NHẤT thành phố. Chỉ ngắm tượng đài từ vỉa hè, tuyệt đối không băng vào vòng xoay; qua đường đúng vạch kẻ và chờ đèn xanh cho người đi bộ.','cong-vien',50,48),
('bao-tang-dak-lak','Bảo tàng Đắk Lắk','bao-tang','Bảo tàng nằm trong toà nhà mô phỏng nhà dài của người Ê Đê, dài như "một tiếng chiêng ngân". Bên trong có cồng chiêng, thuyền độc mộc, voi Tây Nguyên và cả khu rừng thu nhỏ để con khám phá.','8:00–16:30 (nghỉ thứ Hai)','10.000đ, học sinh có thẻ miễn phí',0.9,'Mọi lứa tuổi','Đường Y Ngông có vỉa hè rộng, dễ đi bộ. Đoạn cổng bảo tàng nhiều ô tô ra vào — con đi sát bên trong vỉa hè và quan sát xe rẽ.','bao-tang',44,58),
('nha-day-buon-ma-thuot','Di tích Nhà đày Buôn Ma Thuột','bao-tang','Nhà đày là di tích lịch sử quốc gia đặc biệt, nơi kể câu chuyện về lòng dũng cảm của các chiến sĩ cách mạng. Các phòng trưng bày được phục dựng như thật, vừa học sử vừa như xem phim.','7:30–17:00','Miễn phí',1.2,'Phù hợp từ lớp 3','Đường Tán Thuật khá hẹp và có đoạn không vỉa hè — con đi hàng một, sát lề bên phải, người lớn đi phía ngoài.','bao-tang',56,62),
('dinh-lac-giao','Đình Lạc Giao','bao-tang','Đây là ngôi đình của những người Việt đầu tiên đến lập nghiệp ở Buôn Ma Thuột hơn 90 năm trước. Mái đình cong cong, cột gỗ to — một góc "làng quê Bắc Bộ" ngay giữa phố núi.','7:00–17:00','Miễn phí',0.5,'Mọi lứa tuổi','Đình nằm gần chợ trung tâm, xe máy lên xuống vỉa hè nhiều — con nắm tay người lớn, không chạy nhảy khu vực cổng chợ.','bao-tang',47,54),
('chua-khai-doan','Chùa Sắc Tứ Khải Đoan','bao-tang','Ngôi chùa gỗ lớn nhất Đắk Lắk, được xây từ năm 1951 với mái ngói cong tuyệt đẹp kiểu cung đình Huế. Sân chùa rộng và yên tĩnh, rất nhiều chim bồ câu.','6:00–18:00','Miễn phí',0.8,'Mọi lứa tuổi','Đường Phan Bội Châu một chiều, xe chạy nhanh — con qua đường tại ngã tư có đèn tín hiệu, không băng chéo giữa đường.','bao-tang',42,50),
('bao-tang-ca-phe','Bảo tàng Thế giới Cà phê','bao-tang','Toà nhà cong cong như những chiếc lá úp vào nhau — nơi duy nhất ở Việt Nam kể chuyện cà phê của cả thế giới. Có khu trải nghiệm rang xay và không gian ảnh cực đẹp.','8:00–17:00','30.000đ trẻ em',2.6,'Mọi lứa tuổi','Đường Nguyễn Đình Chiểu rộng, ô tô đông vào cuối tuần. Nếu đi xe đạp, con đi đúng làn sát phải và bật nhớ đội mũ bảo hiểm.','bao-tang',34,40),
('buon-ako-dhong','Buôn Ako Dhông','bao-tang','Buôn làng Ê Đê đẹp nhất thành phố với những ngôi nhà dài truyền thống nằm dưới hàng cây xanh mát. Con sẽ được thấy bến nước, nghe kể chuyện cồng chiêng và thử món cơm lam.','Cả ngày','Miễn phí',2.0,'Mọi lứa tuổi','Đường vào buôn dốc thoai thoải và quanh co — đi bộ theo nhóm sát lề, không thả dốc bằng xe đạp.','thien-nhien',38,32),
('quang-truong-10-3','Quảng trường 10/3','cong-vien','Quảng trường rộng mênh mông để thả diều, trượt patin và xem đài phun nước buổi tối. Cuối tuần có rất nhiều bạn nhỏ ra chơi.','Cả ngày','Miễn phí',0.4,'Mọi lứa tuổi','Bãi xe máy sát mép quảng trường — con chơi ở khu trung tâm, không chơi gần lối xe ra vào; buổi tối mặc đồ sáng màu.','cong-vien',53,44),
('cong-vien-nuoc','Công viên nước Đắk Lắk','vui-choi','Cầu trượt xoắn ốc, dòng sông lười và hồ tạo sóng — chỗ "giải nhiệt" vui nhất thành phố vào ngày nắng. Có khu hồ nông riêng cho các bé nhỏ.','8:00–17:00 (T7, CN đông nhất)','60.000đ trẻ em',3.2,'Đi cùng người lớn','Quãng đường xa, con nên để bố mẹ chở; nhớ đội mũ bảo hiểm cài quai đúng 3 bước và không đùa nghịch khi ngồi sau xe.','vui-choi',28,56),
('duong-sach-ca-phe','Đường sách Cà phê Buôn Ma Thuột','vui-choi','Con phố nhỏ xinh toàn sách, tranh và những quán nước dễ thương — chỗ lý tưởng để đọc truyện tranh ATGT và chụp ảnh cùng bạn bè.','7:00–21:00','Miễn phí',0.4,'Mọi lứa tuổi','Phố đi bộ nhưng hai đầu phố vẫn có xe chạy — con chú ý khi ra vào cổng phố, không mải đọc sách mà bước xuống lòng đường.','vui-choi',49,52),
('khu-vui-choi-thieu-nhi','Nhà Văn hoá Thanh Thiếu nhi Đắk Lắk','vui-choi','Sân chơi quen thuộc của học sinh thành phố: lớp năng khiếu, nhà banh, sân trượt patin và những buổi hội thi vui nhộn — trong đó có cả hội thi an toàn giao thông!','7:00–20:30','Miễn phí (trò chơi tính vé riêng)',1.5,'Mọi lứa tuổi','Giờ tan lớp năng khiếu cổng rất đông — con chờ bố mẹ ở SÂN TRONG, không đứng chờ dưới lòng đường trước cổng.','vui-choi',60,46),
('ho-ea-kao','Hồ Ea Kao','thien-nhien','Hồ nước rộng như biển giữa núi rừng, chiều xuống có đàn cò bay và hoàng hôn tím rực. Nơi cắm trại, dã ngoại cuối tuần được yêu thích nhất.','Cả ngày (đẹp nhất 15:00–18:00)','Miễn phí',12.0,'Đi cùng người lớn','Đường ra hồ xa và có xe tải chạy — bắt buộc bố mẹ chở; ở mép hồ không chơi sát mặt nước, luôn trong tầm mắt người lớn.','thien-nhien',70,70),
('ko-tam','Khu du lịch sinh thái Ko Tam','thien-nhien','Vườn hoa, hồ sen, nhà dài và những trò chơi dân gian Tây Nguyên trong một khu vườn khổng lồ. Mùa nào cũng có hoa để chụp ảnh.','7:00–18:00','20.000đ trẻ em',9.0,'Mọi lứa tuổi','Nằm trên quốc lộ 26 xe container nhiều — chỉ đi bằng ô tô/xe máy cùng người lớn, xuống xe phía trong cổng, không mở cửa xe phía lòng đường.','thien-nhien',78,58),
('thac-dray-nur','Thác Dray Nur','thien-nhien','Ngọn thác hùng vĩ nhất Đắk Lắk — bức tường nước cao 30 mét gầm vang giữa rừng. Truyền thuyết kể đây là nơi trú ngụ của một chàng hoàng tử hoá cá.','7:30–17:00','30.000đ trẻ em',25.0,'Phù hợp từ lớp 3, đi cùng người lớn','Chuyến đi xa 25km — ngồi ô tô nhớ thắt dây an toàn, không thò tay ra cửa sổ; ở thác đi đúng lối có lan can, đá rất trơn.','thien-nhien',85,80),
('buon-don','Khu du lịch Buôn Đôn','thien-nhien','Quê hương của nghề thuần dưỡng voi với cầu treo lắc lư qua sông Sêrêpốk và nhà sàn cổ hơn 130 năm. Một ngày ở Buôn Đôn như một chuyến thám hiểm thật sự!','7:30–17:00','40.000đ trẻ em',40.0,'Phù hợp từ lớp 3, đi cùng người lớn','Chuyến đi cả ngày — kiểm tra dây an toàn trước khi xe chạy; trên cầu treo đi chậm, bám tay vịn, mỗi lượt ít người theo hướng dẫn.','thien-nhien',15,20);
